### ISSUE TITLE
   customisation mednu not appearing in 1.16.5

### ISSUE THREAD

**Issue by jiafeiproducts** [unascribed/Ears#69]

**Comment by hibiii** [comment]
There's no in-game customization menu for Ears, all the customization is done with the skin itself. The only way to do it is using an image editor, and the manipulator (at https://unascribed.com/ears/).

It's a good idea to play around and test with the sample skin to a get a feel of how it works. Once you're done, right click the skin (not the 3D preview) and click "Save Image As...".
